/** Declaration file generated by dts-gen */


declare module 'restify-api-validation'{
    export = restify_api_validation;

    function restify_api_validation(schema: any): any;

    namespace restify_api_validation {
        class ValidationError {
            constructor(errors: any, options: any);

            toJSON(): any;

            toString(): any;

        }

    function options(opts: any): void;

    }
}
declare module 'restify-jwt-community'{
    
    function restify_jwt_community(options: any): any;
    export = restify_jwt_community;
}
